CREATE DATABASE AT5;

CREATE TABLE TabelaEX (
NOME VARCHAR(100) NULL);

CREATE TABLE TabelaFX (
NOME VARCHAR(100) NULL);

--INSERIR DADOS

INSERT INTO TabelaEX VALUES ('Claudia');
INSERT INTO TabelaEX VALUES ('Cadu');
INSERT INTO TabelaEX VALUES ('Bruno');
INSERT INTO TabelaEX VALUES ('Lucineia');
INSERT INTO TabelaEX VALUES ('Augusto');

INSERT INTO TabelaFX VALUES ('Amarildo');
INSERT INTO TabelaFX VALUES ('Alvaro');
INSERT INTO TabelaFX VALUES ('Bruno');
INSERT INTO TabelaFX VALUES ('Damares');
INSERT INTO TabelaFX VALUES ('Augusto');

SELECT EX.NOME, FX.NOME
FROM TabelaEX AS EX
INNER JOIN TabelaFX AS FX
ON EX.NOME = FX.NOME

SELECT EX.NOME, FX.NOME
FROM TabelaEX AS EX
LEFT JOIN TabelaFX AS FX
ON EX.NOME = FX.NOME

SELECT EX.NOME, FX.NOME
FROM TabelaEX AS EX
RIGHT JOIN TabelaFX AS FX
ON EX.NOME = FX.NOME

SELECT EX.NOME, FX.NOME
FROM TABELAEX AS EX
LEFT JOIN TABELAFX AS FX
ON EX.NOME = FX.NOME
WHERE